### PR TITLE
Fix SelectField become un-controlled

### LINKED ISSUE #1010: Bug: SelectField became uncontrolled
### Description of the bug

If I set the value of a SelectField (isMulti = false) to `undefined` the component became un-controlled

### Playroom reproduction

https://playroom.bento.buildo.io/#?code=N4Igxg9gJgpiBcJgApkEoAEBeAfB4AOgHYYaREDOALhgNoBuAhgDYCuMANBhTFQGot2AXWwYASjEZgqAOlY8AylUZUYyVkVgAzAJZEYUNAG5ixUuWoZVlrBnTY8hEqTIRKEZjBnMIAc2QEINZUgcZmLjz8gmoa2noGYc4AviZE4QBOvKzpJAHOpAA8OOEuGAUARqxUVG5WAJ4ADjBYgZXVboEYbgDCzDpgANZYwMFJxfmlGA3pEEwlLgUA9G01ROOTZQowntIAYjrbUPOlTGzNwKfsSccuPQAWjES%2B55ECZ9cTpUSMALbNgZAfOlAjdSMxGOVti0QAB1B5UADkFAwdQg2QwWkY9Ag6R0qlcQIA-CDPi4GuCwDA7h5YOloVsdjRGAScSSNqQIA0qDo3BRhrRQS4nOzJpcYPAMABGDiC0rgyHMCWBCRHEAy0kbAZ6KBKoIAdwgAFo%2BvpAuqRaUeOQoAAZeK6gDEWi0AAY3S6zbKMElzRbhRbSGKJQAmX0B%2BXbXUAITOno1ky1ml1VANxvicYDpCtblt9owgQd7pdzozFp9Xv9AaDGAAzGGLRHFfmQABxTIwNJqr2kRM65spo0mmClgPZzR2-SOt3Ot0j9nl%2BNCD4bRbrBar8KJJJodAfEBJIA

### Version

0.23.1

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by MalpenZibo**
Closes #1010

### CODE REVIEW

File: packages/bento-design-system/src/SelectField/BaseSelect.tsx [hunk 1]
```diff
@@ -74,11 +78,7 @@ export function BaseSelect<A>(props: Props<A>) {
         isDisabled={disabled}
         isReadOnly={isReadOnly || false}
         autoFocus={autoFocus}
-        value={
-          isMulti
-            ? options.filter((o) => ((value ?? []) as readonly A[]).includes(o.value))
-            : options.find((o) => o.value === value)
-        }
+        value={assignValue ? assignValue : null}
```
Comment (gabro) [inline packages/bento-design-system/src/SelectField/BaseSelect.tsx:81]:
```suggestion
        value={assignValue ?? null}
```

**Review by gabro — APPROVED** [review]
Micro-suggestion, otherwise good to go!
